from sqlalchemy import Boolean, Column, Integer, String, Text, Float

from fastapi_crud_orm_connector.utils.rdb_models import Base


class Metadata(Base):
    __tablename__ = "metadata"
    __table_args__ = {'extend_existing': True}
    index = Column(String, primary_key=True, index=True, unique=True)
    heading = Column(Text)
    subheading = Column(Text)
    description = Column(Text)
    continuous = Column(Boolean, default=False)
    map_1 = Column(String)
    map_2 = Column(String)
    map_3 = Column(String)
    map_4 = Column(String)
    map_5 = Column(String)
    map_6 = Column(String)
    map_7 = Column(String)
    map_8 = Column(String)
    map_9 = Column(String)
    map_10 = Column(String)
    map_11 = Column(String)
    map_12 = Column(String)
    map_13 = Column(String)
    map_14 = Column(String)
    map_15 = Column(String)
    map_16 = Column(String)
    map_99 = Column(String)


metadata_model_map = {
    Metadata.__tablename__: Metadata,
}


class NSQuality(Base):
    __tablename__ = "nsquality"
    __table_args__ = {'extend_existing': True}
    id = Column(Integer, primary_key=True, index=True)
    location_postal = Column(String, nullable=True)
    location_region = Column(Integer, nullable=True)
    VOLUNTEER = Column(Integer, nullable=True)
    PARUNION = Column(Integer, nullable=True)
    PARPROASS = Column(Integer, nullable=True)
    PARPOLI = Column(Integer, nullable=True)
    PARSPORT = Column(Integer, nullable=True)
    PARHOBBY = Column(Integer, nullable=True)
    PARRELIG = Column(Integer, nullable=True)
    PARCOMMU = Column(Integer, nullable=True)
    PARSERVE = Column(Integer, nullable=True)
    PARPUBLIC = Column(Integer, nullable=True)
    UNPDHOME = Column(Integer, nullable=True)
    UNPDSHOP = Column(Integer, nullable=True)
    UNPDADMIN = Column(Integer, nullable=True)
    UNPDPERS = Column(Integer, nullable=True)
    UNPDTEACH = Column(Integer, nullable=True)
    RELATVS = Column(Float, nullable=True)
    FRIENDS = Column(Float, nullable=True)
    NEIGHBRS = Column(Float, nullable=True)
    BELONGING = Column(Integer, nullable=True)
    LVG_H1 = Column(Integer, nullable=True)
    LVG_S1 = Column(Integer, nullable=True)
    LVG_N1 = Column(Integer, nullable=True)
    LVG_H2 = Column(Integer, nullable=True)
    LVG_SI1 = Column(Integer, nullable=True)
    LVG_S2 = Column(Integer, nullable=True)
    LVG_N2 = Column(Integer, nullable=True)
    LVG_H3 = Column(Integer, nullable=True)
    LVG_SI2 = Column(Integer, nullable=True)
    LVG_S3 = Column(Integer, nullable=True)
    LVG_N3 = Column(Integer, nullable=True)
    LVG_SI3 = Column(Integer, nullable=True)
    LVG_H4 = Column(Integer, nullable=True)
    LVG_S4 = Column(Integer, nullable=True)
    LVG_N4 = Column(Integer, nullable=True)
    LVG_V1 = Column(Integer, nullable=True)
    SAFE_NBR = Column(Integer, nullable=True)
    TRUST1 = Column(Integer, nullable=True)
    TRUST2 = Column(Integer, nullable=True)
    TRUST4 = Column(Integer, nullable=True)
    TRUST_I1 = Column(Integer, nullable=True)
    TRUST_I2 = Column(Integer, nullable=True)
    TRUST_I3 = Column(Integer, nullable=True)
    TRUST_I4 = Column(Integer, nullable=True)
    TRUST_I5 = Column(Integer, nullable=True)
    TRUST_I6 = Column(Integer, nullable=True)
    CONFID_1 = Column(Integer, nullable=True)
    CONFID_2 = Column(Integer, nullable=True)
    CONFID_3 = Column(Integer, nullable=True)
    CONFID_4 = Column(Integer, nullable=True)
    DISCRIM_1 = Column(Integer, nullable=True)
    DISCRIM_2 = Column(Integer, nullable=True)
    DISCRIM_3 = Column(Integer, nullable=True)
    DISCRIM_4 = Column(Integer, nullable=True)
    DISCRIM_5 = Column(Integer, nullable=True)
    DISCRIM_6 = Column(Integer, nullable=True)
    PHYSHLTH = Column(Integer, nullable=True)
    MNTLHLTH = Column(Integer, nullable=True)
    MH_IMPACT1 = Column(Integer, nullable=True)
    MH_IMPACT2 = Column(Integer, nullable=True)
    MH_IMPACT3 = Column(Integer, nullable=True)
    QUAL_HLTH = Column(Integer, nullable=True)
    ACCESS_HLTH = Column(Integer, nullable=True)
    HB_EXERCISE = Column(Integer, nullable=True)
    HB_NUTRITION = Column(Integer, nullable=True)
    HB_SUBUSE = Column(Integer, nullable=True)
    DU_IMPACT1 = Column(Integer, nullable=True)
    DU_IMPACT2 = Column(Integer, nullable=True)
    DU_IMPACT3 = Column(Integer, nullable=True)
    INT_FED = Column(Integer, nullable=True)
    INT_PROV = Column(Integer, nullable=True)
    INT_LOCAL = Column(Integer, nullable=True)
    DEMPAR_A1 = Column(Integer, nullable=True)
    DEMPAR_A2 = Column(Integer, nullable=True)
    DEMPAR_A3 = Column(Integer, nullable=True)
    DEMPAR_P1 = Column(Integer, nullable=True)
    DEMPAR_C1 = Column(Integer, nullable=True)
    DEMPAR_C2 = Column(Integer, nullable=True)
    DEMPAR_C3 = Column(Integer, nullable=True)
    DEMPAR_P2 = Column(Integer, nullable=True)
    DEMPAR_P3 = Column(Integer, nullable=True)
    POLEFF_1 = Column(Integer, nullable=True)
    POLEFF_2 = Column(Integer, nullable=True)
    POLEFF_3 = Column(Integer, nullable=True)
    POLEFF_4 = Column(Integer, nullable=True)
    POLEFF_5 = Column(Integer, nullable=True)
    POLEFF_6 = Column(Integer, nullable=True)
    POLICY = Column(Integer, nullable=True)
    ENVR_P1 = Column(Integer, nullable=True)
    ENVR_P3 = Column(Integer, nullable=True)
    ENVR_I1 = Column(Integer, nullable=True)
    ENVR_I2 = Column(Integer, nullable=True)
    ENVR_I3 = Column(Integer, nullable=True)
    ENVR_R1 = Column(Integer, nullable=True)
    ENVR_R2 = Column(Integer, nullable=True)
    EN_REUSE = Column(Integer, nullable=True)
    EN_RECYC = Column(Integer, nullable=True)
    EN_REDUC = Column(Integer, nullable=True)
    EN_SEPAR = Column(Integer, nullable=True)
    EN_CONEN = Column(Integer, nullable=True)
    EN_CONWA = Column(Integer, nullable=True)
    EN_WALK = Column(Integer, nullable=True)
    EN_PTRAN = Column(Integer, nullable=True)
    EN_CAR = Column(Integer, nullable=True)
    EN_FOOD = Column(Integer, nullable=True)
    PA_TEAMS = Column(Float, nullable=True)
    PA_INDIV = Column(Float, nullable=True)
    PA_VIGOROUS = Column(Float, nullable=True)
    PA_LIGHTEX = Column(Float, nullable=True)
    SOC_FRND = Column(Float, nullable=True)
    SOC_FILM = Column(Float, nullable=True)
    SOC_CLUB = Column(Float, nullable=True)
    SOC_SPEC = Column(Float, nullable=True)
    HM_READ = Column(Float, nullable=True)
    HM_CARDS = Column(Float, nullable=True)
    HM_PUZZL = Column(Float, nullable=True)
    HM_CRAFT = Column(Float, nullable=True)
    HM_MUSIC = Column(Float, nullable=True)
    CULPAR_1 = Column(Float, nullable=True)
    CULPAR_2 = Column(Float, nullable=True)
    CULPAR_3 = Column(Integer, nullable=True)
    CULPAR_4 = Column(Float, nullable=True)
    CULPAR_5 = Column(Float, nullable=True)
    HM_SURF = Column(Float, nullable=True)
    HM_CGAME = Column(Float, nullable=True)
    HM_CSOC = Column(Float, nullable=True)
    COMPUTE_HR = Column(Float, nullable=True)
    COMPUTE_MIN = Column(Integer, nullable=True)
    TVHOURS = Column(Float, nullable=True)
    TVMIN = Column(Float, nullable=True)
    GAMBLING = Column(Integer, nullable=True)
    FCLUSE_1 = Column(Integer, nullable=True)
    FCLUSE_2 = Column(Integer, nullable=True)
    FCLUSE_3 = Column(Integer, nullable=True)
    FCLUSE_4 = Column(Integer, nullable=True)
    FCLUSE_5 = Column(Integer, nullable=True)
    FCLUSE_7 = Column(Integer, nullable=True)
    FCLUSE_8 = Column(Integer, nullable=True)
    FCLUSE_9 = Column(Integer, nullable=True)
    FCLUSE_10 = Column(Integer, nullable=True)
    FCLUSE_11 = Column(Integer, nullable=True)
    FCLUSE_12 = Column(Integer, nullable=True)
    FCLUSE_13 = Column(Integer, nullable=True)
    FCLUSE_14 = Column(Integer, nullable=True)
    ACSFCL_1 = Column(Integer, nullable=True)
    ACSFCL_2 = Column(Integer, nullable=True)
    ACSFCL_3 = Column(Integer, nullable=True)
    ACSFCL_4 = Column(Integer, nullable=True)
    ACSFCL_5 = Column(Integer, nullable=True)
    ACSFCL_6 = Column(Integer, nullable=True)
    ACSFCL_7 = Column(Integer, nullable=True)
    EDOPP_A1 = Column(Integer, nullable=True)
    EDOPP_A2 = Column(Integer, nullable=True)
    EDOPP_C1 = Column(Integer, nullable=True)
    EDOPP_A3 = Column(Integer, nullable=True)
    EDOPP_A4 = Column(Integer, nullable=True)
    EDOPP_C2 = Column(Integer, nullable=True)
    EDUC_START = Column(Integer, nullable=True)
    EDUC_SKILL = Column(Integer, nullable=True)
    EDUC_PREP = Column(Integer, nullable=True)
    EDUC_QUAL = Column(Integer, nullable=True)
    CRS_INT = Column(Integer, nullable=True)
    CRS_NUMCOM = Column(Float, nullable=True)
    CRS_NUMON = Column(Integer, nullable=True)
    CRS_TRAD = Column(Integer, nullable=True)
    WORKPAY = Column(Integer, nullable=True)
    NUMJOB = Column(Float, nullable=True)
    WORKHR = Column(Float, nullable=True)
    OTHWRKHR = Column(Float, nullable=True)
    FLEXHRS = Column(Integer, nullable=True)
    WORKSCHED = Column(Integer, nullable=True)
    CMTWORK = Column(Float, nullable=True)
    WORK_TRANS = Column(Integer, nullable=True)
    JOB_JP1 = Column(Integer, nullable=True)
    JOB_JP2 = Column(Integer, nullable=True)
    JOB_JP3 = Column(Integer, nullable=True)
    JOB_JS1 = Column(Integer, nullable=True)
    JOB_JP4 = Column(Integer, nullable=True)
    JOB_JS2 = Column(Integer, nullable=True)
    JOB_JM1 = Column(Integer, nullable=True)
    WK_WIPL1 = Column(Integer, nullable=True)
    WK_WIPL2 = Column(Integer, nullable=True)
    WK_WIPL3 = Column(Integer, nullable=True)
    WK_WIPL4 = Column(Integer, nullable=True)
    WK_WIPL5 = Column(Integer, nullable=True)
    WK_WIPL6 = Column(Integer, nullable=True)
    WK_PLIW1 = Column(Integer, nullable=True)
    WK_PLIW2 = Column(Integer, nullable=True)
    WK_PLIW3 = Column(Integer, nullable=True)
    WK_PLIW4 = Column(Integer, nullable=True)
    WK_WPLE1 = Column(Integer, nullable=True)
    WK_WPLE2 = Column(Integer, nullable=True)
    WK_WPLE3 = Column(Integer, nullable=True)
    EXP_BILL = Column(Integer, nullable=True)
    EXP_HOME = Column(Integer, nullable=True)
    EXP_FOOD = Column(Integer, nullable=True)
    EXP_NFOOD = Column(Integer, nullable=True)
    EXP_FOODBK = Column(Integer, nullable=True)
    EXP_TRANS = Column(Integer, nullable=True)
    EXP_WANT = Column(Integer, nullable=True)
    EXP_NEED = Column(Integer, nullable=True)
    INTERNET = Column(Integer, nullable=True)
    NET_QUAL = Column(Integer, nullable=True)
    CHLDCARE = Column(Integer, nullable=True)
    CHLDFAM = Column(Float, nullable=True)
    CHLDOTH = Column(Float, nullable=True)
    CHLDC_ADQ = Column(Integer, nullable=True)
    SRCARE = Column(Integer, nullable=True)
    SRCARFAM = Column(Float, nullable=True)
    SRCAROTH = Column(Float, nullable=True)
    SRC_ADQ = Column(Integer, nullable=True)
    RUSHED = Column(Integer, nullable=True)
    TIMEREST = Column(Integer, nullable=True)
    TIMESELF = Column(Integer, nullable=True)
    TIMESOC = Column(Integer, nullable=True)
    TIMEPHYS = Column(Integer, nullable=True)
    TIMEMEAL = Column(Integer, nullable=True)
    TIMECOMM = Column(Integer, nullable=True)
    TIMENURT = Column(Integer, nullable=True)
    TIMECHOR = Column(Integer, nullable=True)
    TIMEKIDS = Column(Integer, nullable=True)
    TIMESPOU = Column(Integer, nullable=True)
    TIMEFAML = Column(Integer, nullable=True)
    TIMERELA = Column(Integer, nullable=True)
    TIMECREA = Column(Integer, nullable=True)
    SLEEP = Column(Float, nullable=True)
    VACADAYS = Column(Float, nullable=True)
    WBI1MNTL = Column(Integer, nullable=True)
    WBI2PHYS = Column(Integer, nullable=True)
    WBI3LEIS = Column(Integer, nullable=True)
    WBE1COMM = Column(Integer, nullable=True)
    WBI4PERS = Column(Integer, nullable=True)
    WBE2EDUC = Column(Integer, nullable=True)
    WBI7BAL = Column(Integer, nullable=True)
    WBI8TIME = Column(Integer, nullable=True)
    WBE3ARTS = Column(Integer, nullable=True)
    WBE4REC = Column(Integer, nullable=True)
    WBE5NBHD = Column(Integer, nullable=True)
    WBE6ENV = Column(Integer, nullable=True)
    WBE7GOV = Column(Integer, nullable=True)
    WBE8DEM = Column(Integer, nullable=True)
    WBI5FIN = Column(Integer, nullable=True)
    WBI6WORK = Column(Integer, nullable=True)
    LIFEWRTH = Column(Float, nullable=True)
    LIFESAT = Column(Integer, nullable=True)
    SEX = Column(Integer, nullable=True)
    GENDER = Column(Integer, nullable=True)
    SEXORIENT = Column(Integer, nullable=True)
    AGE = Column(Float, nullable=True)
    MARSTAT = Column(Integer, nullable=True)
    EDUCAT = Column(Integer, nullable=True)
    MAINACT = Column(Integer, nullable=True)
    INCOME = Column(Integer, nullable=True)
    BORN_CAN = Column(Integer, nullable=True)
    CITIZEN = Column(Integer, nullable=True)
    YEARS_CAN = Column(Float, nullable=True)
    ETHNIC1 = Column(Integer, nullable=True)
    FIRST_LANG = Column(Integer, nullable=True)
    HOME_LANG = Column(Integer, nullable=True)
    FN_STATUS = Column(Integer, nullable=True)
    DISABILITY = Column(Integer, nullable=True)
    LIMIT_PART1 = Column(Integer, nullable=True)
    LIMIT_PART2 = Column(Integer, nullable=True)
    LIMIT_PART3 = Column(Integer, nullable=True)
    RESCOMYR = Column(Integer, nullable=True)
    RESCOMMO = Column(Float, nullable=True)
    RESCURYR = Column(Float, nullable=True)
    RESCURMO = Column(Float, nullable=True)
    RES_ORL = Column(Integer, nullable=True)
    MAIN_TRANS = Column(Integer, nullable=True)
    RES_SPND = Column(Integer, nullable=True)
    PARTHAVE = Column(Integer, nullable=True)
    PARTLIVE = Column(Integer, nullable=True)
    PART_GEN = Column(Integer, nullable=True)
    HHOLD_TYPE = Column(Integer, nullable=True)
    KIDS_U5 = Column(Integer, nullable=True)
    KIDS_5TO12 = Column(Integer, nullable=True)
    KIDS_13TO18 = Column(Integer, nullable=True)
    KIDS_OVER18 = Column(Integer, nullable=True)
    WGHT = Column(Float, nullable=True)
    R_RELATVS = Column(Float, nullable=True)
    R_FRIENDS = Column(Float, nullable=True)
    R_NEIGHBRS = Column(Float, nullable=True)
    R_PA_TEAMS = Column(Float, nullable=True)
    R_PA_INDIV = Column(Float, nullable=True)
    R_PA_VIGOROUS = Column(Float, nullable=True)
    R_PA_LIGHTEX = Column(Float, nullable=True)
    R_SOC_FRND = Column(Float, nullable=True)
    R_SOC_FILM = Column(Float, nullable=True)
    R_SOC_CLUB = Column(Float, nullable=True)
    R_SOC_SPEC = Column(Float, nullable=True)
    R_HM_READ = Column(Float, nullable=True)
    R_HM_CARDS = Column(Float, nullable=True)
    R_HM_PUZZL = Column(Float, nullable=True)
    R_HM_CRAFT = Column(Float, nullable=True)
    R_HM_MUSIC = Column(Float, nullable=True)
    R_CULPAR_1 = Column(Float, nullable=True)
    R_CULPAR_2 = Column(Float, nullable=True)
    R_CULPAR_3 = Column(Float, nullable=True)
    R_CULPAR_4 = Column(Float, nullable=True)
    R_CULPAR_5 = Column(Float, nullable=True)
    R_HM_SURF = Column(Float, nullable=True)
    R_HM_CGAME = Column(Float, nullable=True)
    R_HM_CSOC = Column(Float, nullable=True)
    R_CRS_NUMCOM = Column(Integer, nullable=True)
    R_CRS_NUMON = Column(Integer, nullable=True)
    R_NUMJOB = Column(Float, nullable=True)
    R_WORKHR = Column(Float, nullable=True)
    R_OTHWRKHR = Column(Integer, nullable=True)
    R_CMTWORK = Column(Float, nullable=True)
    R_CHLDOTH = Column(Float, nullable=True)
    R_SRCARFAM = Column(Float, nullable=True)
    R_SRCAROTH = Column(Float, nullable=True)
    R_SLEEP = Column(Float, nullable=True)
    R_VACADAYS = Column(Float, nullable=True)
    R_KIDS_U5 = Column(Integer, nullable=True)
    R_KIDS_5TO12 = Column(Integer, nullable=True)
    R_KIDS_13TO18 = Column(Integer, nullable=True)
    R_KIDS_OVER18 = Column(Integer, nullable=True)
    COMYEARS = Column(Float, nullable=True)
    RESYEARS = Column(Float, nullable=True)
    TV_TIME = Column(Float, nullable=True)
    COMP_TIME = Column(Float, nullable=True)
    SOCIAL_CLIMATE = Column(Float, nullable=True)
    SOC_HELP = Column(Float, nullable=True)
    SOC_NEEDS = Column(Float, nullable=True)
    OVERALL_SOC = Column(Float, nullable=True)
    SOCIAL_ISO = Column(Float, nullable=True)
    POLEFFICACY = Column(Float, nullable=True)
    SECURITY = Column(Float, nullable=True)
    PROMOTION = Column(Float, nullable=True)
    OVERALL_JF = Column(Float, nullable=True)
    WL_ENHANCE = Column(Float, nullable=True)
    WK_INTERF = Column(Float, nullable=True)
    PL_INTERF = Column(Float, nullable=True)
    WL_BALANCE = Column(Float, nullable=True)
    TIME_ADEQ = Column(Float, nullable=True)
    CV = Column(Float, nullable=True)
    DE = Column(Float, nullable=True)
    ED = Column(Integer, nullable=True)
    ENV = Column(Float, nullable=True)
    HP = Column(Float, nullable=True)
    LC = Column(Float, nullable=True)
    LS = Column(Float, nullable=True)
    TU = Column(Float, nullable=True)
    CIW_WELLB = Column(Float, nullable=True)


nsquality_model_map = {
    NSQuality.__tablename__: NSQuality,
}
