""""first"

Revision ID: 12ddabd37746
Revises: 
Create Date: 2021-01-15 17:50:53.438288

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '12ddabd37746'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('first_name', sa.String(), nullable=True),
                    sa.Column('last_name', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_author_id'), 'author', ['id'], unique=False)
    op.create_table('project',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('overleaf', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('overleaf')
                    )
    op.create_index(op.f('ix_project_id'), 'project', ['id'], unique=False)
    op.create_index(op.f('ix_project_name'), 'project', ['name'], unique=True)
    op.create_table('publication',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('citation', sa.String(), nullable=False),
                    sa.Column('title', sa.String(), nullable=False),
                    sa.Column('journal', sa.String(), nullable=False),
                    sa.Column('link', sa.String(), nullable=False),
                    sa.Column('bibtex', sa.Text(), nullable=False),
                    sa.Column('summary', sa.Text(), nullable=False),
                    sa.Column('abstract', sa.Text(), nullable=False),
                    sa.Column('notes', sa.Text(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_publication_citation'), 'publication', ['citation'], unique=True)
    op.create_index(op.f('ix_publication_id'), 'publication', ['id'], unique=False)
    op.create_index(op.f('ix_publication_title'), 'publication', ['title'], unique=True)
    op.create_table('user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.Column('first_name', sa.String(), nullable=True),
                    sa.Column('last_name', sa.String(), nullable=True),
                    sa.Column('hashed_password', sa.String(), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('is_superuser', sa.Boolean(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('author_publication_association',
                    sa.Column('author_id', sa.Integer(), nullable=False),
                    sa.Column('publication_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['author_id'], ['author.id'], ),
                    sa.ForeignKeyConstraint(['publication_id'], ['publication.id'], ),
                    sa.PrimaryKeyConstraint('author_id', 'publication_id')
                    )
    op.create_table('project_publication_association',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('publication_id', sa.Integer(), nullable=True),
                    sa.Column('project_id', sa.Integer(), nullable=True),
                    sa.Column('summary', sa.Text(), nullable=False),
                    sa.Column('notes', sa.Text(), nullable=False),
                    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['publication_id'], ['publication.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_project_publication_association_id'), 'project_publication_association', ['id'], unique=False)
    op.drop_table('alembic_version', schema='main')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alembic_version',
                    sa.Column('version_num', sa.VARCHAR(length=32), nullable=False),
                    sa.PrimaryKeyConstraint('version_num', name='alembic_version_pkc'),
                    schema='main'
                    )
    op.drop_index(op.f('ix_project_publication_association_id'), table_name='project_publication_association')
    op.drop_table('project_publication_association')
    op.drop_table('author_publication_association')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_publication_title'), table_name='publication')
    op.drop_index(op.f('ix_publication_id'), table_name='publication')
    op.drop_index(op.f('ix_publication_citation'), table_name='publication')
    op.drop_table('publication')
    op.drop_index(op.f('ix_project_name'), table_name='project')
    op.drop_index(op.f('ix_project_id'), table_name='project')
    op.drop_table('project')
    op.drop_index(op.f('ix_author_id'), table_name='author')
    op.drop_table('author')
    # ### end Alembic commands ###
