""""first"

Revision ID: 6b51239bbceb
Revises: 9e4161286012
Create Date: 2021-01-25 10:58:23.342448

"""
from datetime import datetime

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b51239bbceb'
down_revision = '9e4161286012'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publication', sa.Column('time_created', sa.DateTime(timezone=True),
                                           server_default=sa.text('(CURRENT_TIMESTAMP)'),
                                           default=datetime.now().timestamp(), nullable=True))
    op.add_column('publication', sa.Column('time_updated', sa.DateTime(timezone=True),
                                           default=datetime.now().timestamp(),
                                           server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publication', 'time_updated')
    op.drop_column('publication', 'time_created')
    # ### end Alembic commands ###
