"""first

Revision ID: 70019319e716
Revises: 6b51239bbceb
Create Date: 2021-01-26 13:19:07.659380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70019319e716'
down_revision = '6b51239bbceb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publication', sa.Column('keywords', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publication', 'keywords')
    # ### end Alembic commands ###
