""""first"

Revision ID: 9e4161286012
Revises: 12ddabd37746
Create Date: 2021-01-15 19:20:47.013259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e4161286012'
down_revision = '12ddabd37746'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_publication_association', sa.Column('inserted', sa.Boolean(), nullable=True))
    op.execute("UPDATE project_publication_association SET inserted = false")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_publication_association', 'inserted')
    # ### end Alembic commands ###
