"""first

Revision ID: f09cf62a8183
Revises: 70019319e716
Create Date: 2021-01-28 23:18:29.031866

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'f09cf62a8183'
down_revision = '70019319e716'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_publication_association',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('publication_id', sa.Integer(), nullable=True),
                    sa.Column('project_id', sa.Integer(), nullable=True),
                    sa.Column('summary', sa.Text(), nullable=False),
                    sa.Column('notes', sa.Text(), nullable=False),
                    sa.Column('inserted', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['publication_id'], ['publication.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_project_publication_association_id'), 'project_publication_association', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_publication_association_id'), table_name='project_publication_association')
    op.drop_table('project_publication_association')
    # ### end Alembic commands ###
